from __future__ import annotations

import hashlib
import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pymupdf

from kbparse.images.assets import make_asset_path
from kbparse.models import Document, Element, Page, ParserInfo, Source


class DoclingParser:
    """Docling adapter for richer PDF layout extraction.

    Docling is intentionally optional because it is a heavier dependency than
    PyMuPDF. This adapter converts Docling's exported Markdown/dict artifacts
    into KBParse's canonical schema so Markdown/chunks remain generated by the
    KBParse pipeline, not by blindly chunking Docling output.
    """

    name = "docling"
    version = "0.1.0"

    def __init__(self, converter_factory: Callable[[], Any] | None = None):
        self._converter_factory = converter_factory or self._default_converter_factory

    def parse(self, pdf_path: str | Path, output_doc_dir: str | Path) -> Document:
        pdf_path = Path(pdf_path)
        output_doc_dir = Path(output_doc_dir)
        artifacts_dir = output_doc_dir / "parse_artifacts"
        artifacts_dir.mkdir(parents=True, exist_ok=True)

        try:
            converter = self._converter_factory()
        except ImportError as exc:
            raise RuntimeError(
                "Install Docling to use --parser docling, for example: "
                "uv add docling or uv run --with docling kbparse ..."
            ) from exc

        result = converter.convert(str(pdf_path))
        docling_doc = result.document
        raw = self._export_dict(docling_doc)
        (artifacts_dir / "docling_document.json").write_text(
            json.dumps(raw, ensure_ascii=False, indent=2, default=str),
            encoding="utf-8",
        )

        markdown = self._export_markdown(docling_doc)
        pages = self._pages_from_raw(raw)
        elements = self._elements_from_raw(raw, pages, pdf_path, output_doc_dir)
        if not elements:
            elements = self._elements_from_markdown(markdown)
        sha = hashlib.sha256(pdf_path.read_bytes()).hexdigest() if pdf_path.exists() else None

        return Document(
            doc_id=pdf_path.stem,
            source=Source(path=str(pdf_path), sha256=sha),
            pages=pages,
            elements=elements,
            parser=ParserInfo(name=self.name, version=self.version),
        )

    def _default_converter_factory(self):
        from docling.document_converter import DocumentConverter

        return DocumentConverter()

    def _export_dict(self, docling_doc: Any) -> dict[str, Any]:
        if hasattr(docling_doc, "export_to_dict"):
            data = docling_doc.export_to_dict()
            return data if isinstance(data, dict) else {"docling": data}
        return {"warning": "Docling document has no export_to_dict"}

    def _export_markdown(self, docling_doc: Any) -> str:
        if hasattr(docling_doc, "export_to_markdown"):
            return str(docling_doc.export_to_markdown())
        if hasattr(docling_doc, "export_to_text"):
            return str(docling_doc.export_to_text())
        return ""

    def _pages_from_raw(self, raw: dict[str, Any]) -> list[Page]:
        pages_raw = raw.get("pages") or raw.get("page") or []
        pages: list[Page] = []
        if isinstance(pages_raw, dict):
            iterable = sorted(pages_raw.items(), key=lambda item: str(item[0]))
            for idx, (_, page_data) in enumerate(iterable, start=1):
                width, height = self._page_size(page_data)
                pages.append(Page(page_num=idx, width=width, height=height))
        elif isinstance(pages_raw, list):
            for idx, page_data in enumerate(pages_raw, start=1):
                width, height = self._page_size(page_data)
                pages.append(Page(page_num=idx, width=width, height=height))
        if not pages:
            pages.append(Page(page_num=1, width=0.0, height=0.0))
        return pages

    def _page_size(self, page_data: Any) -> tuple[float, float]:
        if not isinstance(page_data, dict):
            return 0.0, 0.0
        size = page_data.get("size") or page_data.get("page_size") or page_data.get("dimensions") or {}
        if isinstance(size, dict):
            width = size.get("width") or size.get("w") or 0.0
            height = size.get("height") or size.get("h") or 0.0
            return float(width or 0.0), float(height or 0.0)
        return 0.0, 0.0

    def _elements_from_raw(self, raw: dict[str, Any], pages: list[Page], pdf_path: Path, output_doc_dir: Path) -> list[Element]:
        ref_index = self._ref_index(raw)
        captions = self._caption_candidates(raw, pages)
        picture_counts: dict[int, int] = {}
        table_counts: dict[int, int] = {}
        children = (((raw.get("body") or {}).get("children")) or [])
        elements: list[Element] = []
        reading_order = 1
        for child in children:
            ref = child.get("$ref") if isinstance(child, dict) else None
            node = ref_index.get(ref or "")
            if not isinstance(node, dict):
                continue
            element = self._element_from_raw_node(
                node,
                ref or node.get("self_ref") or "",
                reading_order,
                pages,
                pdf_path,
                output_doc_dir,
                captions,
                picture_counts,
                table_counts,
            )
            if element is None:
                continue
            elements.append(element)
            reading_order += 1
        return elements

    def _ref_index(self, raw: dict[str, Any]) -> dict[str, dict[str, Any]]:
        index: dict[str, dict[str, Any]] = {}
        for collection in ["texts", "tables", "pictures"]:
            items = raw.get(collection) or []
            if not isinstance(items, list):
                continue
            for i, item in enumerate(items):
                if not isinstance(item, dict):
                    continue
                ref = item.get("self_ref") or f"#/{collection}/{i}"
                index[str(ref)] = item
                index[f"#/{collection}/{i}"] = item
        return index

    def _element_from_raw_node(
        self,
        node: dict[str, Any],
        ref: str,
        reading_order: int,
        pages: list[Page],
        pdf_path: Path,
        output_doc_dir: Path,
        captions: list[dict[str, Any]],
        picture_counts: dict[int, int],
        table_counts: dict[int, int],
    ) -> Element | None:
        label = str(node.get("label") or "").lower()
        prov = self._first_prov(node)
        page_no = int(prov.get("page_no") or 1) if prov else 1
        page = next((p for p in pages if p.page_num == page_no), None)
        bbox = self._normalize_docling_bbox(prov.get("bbox") if prov else None, page)
        metadata = {"docling_ref": ref, "docling_label": label}
        source = {"parser": self.name, "docling_ref": ref}

        if ref.startswith("#/pictures/") or label in {"picture", "figure"}:
            picture_counts[page_no] = picture_counts.get(page_no, 0) + 1
            image_idx = picture_counts[page_no]
            asset_path = make_asset_path(page_no, "figure", image_idx, ext="png")
            self._crop_pdf_region(pdf_path, output_doc_dir / asset_path, page_no, prov.get("bbox") if prov else None)
            caption = self._nearest_caption(captions, page_no, bbox)
            return Element(
                element_id=f"p{page_no:04d}_fig{image_idx:03d}",
                type="figure",
                page=page_no,
                bbox=bbox,
                reading_order=reading_order,
                section_path=[],
                asset_path=asset_path,
                markdown=f"![圖片：第 {page_no} 頁圖 {image_idx}，待描述]({asset_path})",
                caption_nearby=caption,
                description_status="pending",
                metadata={**metadata, "parser_block_type": "docling_picture"},
                source={**source, "crop_method": "docling_bbox_page_render"},
            )

        if ref.startswith("#/tables/") or label == "table":
            table_counts[page_no] = table_counts.get(page_no, 0) + 1
            table_idx = table_counts[page_no]
            asset_path = make_asset_path(page_no, "table", table_idx, ext="png")
            self._crop_pdf_region(pdf_path, output_doc_dir / asset_path, page_no, prov.get("bbox") if prov else None)
            table_cells = self._table_cells(node)
            table_html = self._table_html(node)
            caption = self._nearest_caption(captions, page_no, bbox)
            text = self._table_markdown(node)
            table_metadata = {
                **metadata,
                "parser_block_type": "docling_table",
                "table_cells": table_cells,
            }
            if table_html:
                table_metadata["table_html"] = table_html
            return Element(
                element_id=f"p{page_no:04d}_table{table_idx:03d}",
                type="table",
                page=page_no,
                bbox=bbox,
                reading_order=reading_order,
                text=text,
                asset_path=asset_path,
                caption_nearby=caption,
                metadata=table_metadata,
                source={**source, "crop_method": "docling_bbox_page_render"},
            )

        text = str(node.get("text") or node.get("orig") or "").strip()
        if not text:
            return None
        if label in {"section_header", "title"}:
            element_type = "heading"
            parser_block_type = "docling_heading"
            extra_metadata = {"level": 1}
        elif label == "caption":
            element_type = "caption"
            parser_block_type = "docling_caption"
            extra_metadata = {}
        elif label in {"list_item", "enumerated_list", "bullet_list"}:
            element_type = "list"
            parser_block_type = "docling_list"
            extra_metadata = {}
        else:
            element_type = "paragraph"
            parser_block_type = "docling_text"
            extra_metadata = {}
        return Element(
            element_id=f"p{page_no:04d}_docling{reading_order:03d}",
            type=element_type,
            page=page_no,
            bbox=bbox,
            reading_order=reading_order,
            text=text,
            metadata={**metadata, **extra_metadata, "parser_block_type": parser_block_type},
            source=source,
        )

    def _first_prov(self, node: dict[str, Any]) -> dict[str, Any]:
        prov = node.get("prov") or []
        if isinstance(prov, list) and prov and isinstance(prov[0], dict):
            return prov[0]
        return {}

    def _caption_candidates(self, raw: dict[str, Any], pages: list[Page]) -> list[dict[str, Any]]:
        candidates: list[dict[str, Any]] = []
        for item in raw.get("texts") or []:
            if not isinstance(item, dict) or str(item.get("label") or "").lower() != "caption":
                continue
            prov = self._first_prov(item)
            page_no = int(prov.get("page_no") or 1) if prov else 1
            page = next((p for p in pages if p.page_num == page_no), None)
            bbox = self._normalize_docling_bbox(prov.get("bbox") if prov else None, page)
            text = str(item.get("text") or item.get("orig") or "").strip()
            if text:
                candidates.append({"page": page_no, "bbox": bbox, "text": text})
        return candidates

    def _nearest_caption(self, captions: list[dict[str, Any]], page_no: int, bbox: list[float] | None) -> str | None:
        same_page = [c for c in captions if c["page"] == page_no]
        if not same_page:
            return None
        if bbox is None:
            return same_page[0]["text"]
        cx = (bbox[0] + bbox[2]) / 2
        cy = (bbox[1] + bbox[3]) / 2
        def distance(caption: dict[str, Any]) -> float:
            cb = caption.get("bbox")
            if not cb:
                return 0.0
            ccx = (cb[0] + cb[2]) / 2
            ccy = (cb[1] + cb[3]) / 2
            return abs(cx - ccx) + abs(cy - ccy)
        return min(same_page, key=distance)["text"]

    def _crop_pdf_region(self, pdf_path: Path, output_path: Path, page_no: int, bbox: Any) -> None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        if not isinstance(bbox, dict):
            output_path.write_bytes(b"")
            return
        try:
            with pymupdf.open(pdf_path) as pdf:
                page = pdf[page_no - 1]
                rect = self._docling_bbox_to_page_rect(bbox, float(page.rect.height))
                pix = page.get_pixmap(matrix=pymupdf.Matrix(2, 2), clip=rect, alpha=False)
                pix.save(output_path)
        except Exception:
            output_path.write_bytes(b"")

    def _docling_bbox_to_page_rect(self, bbox: dict[str, Any], page_height: float) -> pymupdf.Rect:
        left = float(bbox.get("l") or bbox.get("left") or 0.0)
        right = float(bbox.get("r") or bbox.get("right") or 0.0)
        top = float(bbox.get("t") or bbox.get("top") or 0.0)
        bottom = float(bbox.get("b") or bbox.get("bottom") or 0.0)
        origin = str(bbox.get("coord_origin") or "").upper()
        if origin == "BOTTOMLEFT":
            y0 = page_height - top
            y1 = page_height - bottom
        else:
            y0 = top
            y1 = bottom
        return pymupdf.Rect(left, min(y0, y1), right, max(y0, y1))

    def _normalize_docling_bbox(self, bbox: Any, page: Page | None) -> list[float] | None:
        if not isinstance(bbox, dict) or page is None or page.width <= 0 or page.height <= 0:
            return None
        left = float(bbox.get("l") or bbox.get("left") or 0.0)
        right = float(bbox.get("r") or bbox.get("right") or 0.0)
        top = float(bbox.get("t") or bbox.get("top") or 0.0)
        bottom = float(bbox.get("b") or bbox.get("bottom") or 0.0)
        origin = str(bbox.get("coord_origin") or "").upper()
        if origin == "BOTTOMLEFT":
            y0 = (page.height - top) / page.height
            y1 = (page.height - bottom) / page.height
        else:
            y0 = top / page.height
            y1 = bottom / page.height
        x0 = left / page.width
        x1 = right / page.width
        return [
            round(max(0.0, min(1.0, x0)), 6),
            round(max(0.0, min(1.0, min(y0, y1))), 6),
            round(max(0.0, min(1.0, x1)), 6),
            round(max(0.0, min(1.0, max(y0, y1))), 6),
        ]

    def _table_cells(self, node: dict[str, Any]) -> list[dict[str, Any]]:
        data = node.get("data") if isinstance(node.get("data"), dict) else {}
        cells = data.get("table_cells") or node.get("table_cells") or []
        return [cell for cell in cells if isinstance(cell, dict)] if isinstance(cells, list) else []

    def _table_html(self, node: dict[str, Any]) -> str | None:
        data = node.get("data") if isinstance(node.get("data"), dict) else {}
        for value in [data.get("html"), data.get("table_html"), node.get("html"), node.get("table_html")]:
            if value:
                return str(value)
        return None

    def _table_markdown(self, node: dict[str, Any]) -> str:
        cells = self._table_cells(node)
        if not isinstance(cells, list) or not cells:
            return str(node.get("text") or "").strip()
        max_row = 0
        max_col = 0
        for cell in cells:
            if not isinstance(cell, dict):
                continue
            max_row = max(max_row, int(cell.get("end_row_offset_idx") or cell.get("row") or 1))
            max_col = max(max_col, int(cell.get("end_col_offset_idx") or cell.get("col") or 1))
        grid = [["" for _ in range(max_col)] for _ in range(max_row)]
        for cell in cells:
            if not isinstance(cell, dict):
                continue
            row = int(cell.get("start_row_offset_idx") or cell.get("row") or 0)
            col = int(cell.get("start_col_offset_idx") or cell.get("col") or 0)
            if 0 <= row < max_row and 0 <= col < max_col:
                grid[row][col] = str(cell.get("text") or "").replace("\n", " ").strip()
        if not grid:
            return ""
        header = grid[0]
        sep = ["---" for _ in header]
        rows = grid[1:]
        lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(sep) + " |"]
        lines.extend("| " + " | ".join(row) + " |" for row in rows)
        return "\n".join(lines)

    def _elements_from_markdown(self, markdown: str) -> list[Element]:
        blocks = [block.strip() for block in markdown.split("\n\n") if block.strip()]
        elements: list[Element] = []
        reading_order = 1
        for block in blocks:
            element = self._element_from_markdown_block(block, reading_order)
            elements.append(element)
            reading_order += 1
        return elements

    def _element_from_markdown_block(self, block: str, reading_order: int) -> Element:
        first_line = block.splitlines()[0].strip()
        if first_line.startswith("#"):
            level = len(first_line) - len(first_line.lstrip("#"))
            text = first_line[level:].strip()
            return Element(
                element_id=f"p0001_docling{reading_order:03d}",
                type="heading",
                page=1,
                bbox=None,
                reading_order=reading_order,
                text=text,
                metadata={"level": max(1, min(level, 6)), "parser_block_type": "markdown_heading"},
                source={"parser": self.name},
            )
        if self._looks_like_markdown_table(block):
            return Element(
                element_id=f"p0001_docling{reading_order:03d}",
                type="table",
                page=1,
                bbox=None,
                reading_order=reading_order,
                text=block,
                metadata={"parser_block_type": "markdown_table"},
                source={"parser": self.name},
            )
        return Element(
            element_id=f"p0001_docling{reading_order:03d}",
            type="paragraph",
            page=1,
            bbox=None,
            reading_order=reading_order,
            text=block,
            metadata={"parser_block_type": "markdown_paragraph"},
            source={"parser": self.name},
        )

    def _looks_like_markdown_table(self, block: str) -> bool:
        lines = [line.strip() for line in block.splitlines() if line.strip()]
        return len(lines) >= 2 and all(line.startswith("|") and line.endswith("|") for line in lines[:2])
